change APIC to have scalar/vector p2g/g2p interpolation with single P…
picassodev/picasso pull request #61
Opened 2022-04-22 03:41 UTC by kwitaechong

modify APIC to have scalar/vector p2g/g2p interpolation with single ParticleField. ParticleField c_p is composed of

for vector field
c_p[4,3] matrix = u_p[1, 3] matrix  + B_p[3, 3] matrix ( combined by row )

for scalar field
c_p[4,1] matrix = u_p[1, 1] matrix   + B_p[3, 1] matrix ( combined by row )

2022-04-22 18:15 UTC, streeve requested changes
Will likely not pass until #62 is fixed and merged

2022-05-02 21:52 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +p2g( const ParticleMass& m_p, const ParticleField& c_p, const GridField& mu_i,
done

2022-05-02 21:52 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +        // transpose of c_p is already taken accounted in B_p
// B_p is sliced from c_p and is transposed to make matrix multiplication feasible.

2022-05-02 21:52 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    static_assert( 4 == ParticleField::extent_0, "APIC 4 modes" );
done

2022-05-02 21:52 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    static_assert( 4 == ParticleField::extent_0, "APIC 4 modes" );
done

2022-05-02 21:55 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    static_assert( 3 == ParticleField::extent_1,
I need to ask this to @sslattery. It seems to me that  this p2g interpolation on staggered grid is only valid for vector interpolation

2022-05-02 21:56 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    static_assert( 3 == ParticleField::extent_1,
same. p2g interpolation on staggered grid seems valid only for 3d vector

2022-05-02 21:56 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    for ( int d = 0; d < ncomp; ++d )
yes

2022-05-02 22:06 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +template <class ParticleMass, class ParticleField, class SplineDataType,
done

2022-05-03 02:00 UTC, dalg24 commented on src/Picasso_APIC.hpp
> +    static constexpr int ncomp = ParticleField::extent_1;
```suggestion
    constexpr int ncomp = ParticleField::extent_1;
```

2022-05-03 13:50 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    static constexpr int ncomp = ParticleField::extent_1;
done

2022-05-03 17:51 UTC, sslattery approved these changes

2022-05-03 17:51 UTC, sslattery commented on src/Picasso_APIC.hpp
> +    static_assert( 3 == ParticleField::extent_1,
Yes this is really just for momentum updates on staggered grids

2022-05-03 17:51 UTC, sslattery commented on src/Picasso_APIC.hpp
> +    static_assert( 3 == ParticleField::extent_1,
correct - just for momentum updates on staggered grids

2022-05-03 17:51 UTC, sslattery commented on src/Picasso_APIC.hpp
> +    for ( int d = 0; d < ncomp; ++d )
Yes - this is OK for now though. I like how you have unified the scalar/vector implementations.

2022-05-03 17:59 UTC, streeve reviewed
Would be nice to have add an APIC scalar test, but not sure how much effort that would take

2022-05-03 17:59 UTC, streeve commented on src/Picasso_APIC.hpp
> +    static_assert( 3 == ParticleField::extent_1,
Oh okay, then we should just rename to `Particle/GridMomentum` in the staggered overloads then

2022-05-03 19:42 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    static_assert( 3 == ParticleField::extent_1,
done

2022-05-03 19:43 UTC, kwitaechong commented
> Would be nice to have add an APIC scalar test, but not sure how much effort that would take

2022-05-04 16:23 UTC, streeve commented on src/Picasso_APIC.hpp
>  // Interpolate particle momentum and mass to a collocated momentum
"particle property" / "grid property"

2022-05-04 16:23 UTC, streeve commented on src/Picasso_APIC.hpp
> +// data.ParticleVelocity matrix c_p (4*N matrix) is composed of particle field
4x3, 1x3, & 3x3

2022-05-04 16:25 UTC, streeve commented on src/Picasso_APIC.hpp
> -    auto momentum_access = mu_i.access();
Same here

2022-05-04 16:34 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> -    auto momentum_access = mu_i.access();
done

2022-05-04 16:34 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> -    auto momentum_access = mu_i.access();
done

2022-05-04 16:34 UTC, kwitaechong commented on src/Picasso_APIC.hpp
>  // Interpolate particle momentum and mass to a collocated momentum
done

2022-05-05 20:20 UTC, streeve reviewed
Does this run on Summit? Not sure about the Cuda failure

2022-05-06 14:28 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> -// Interpolate staggered grid velocity to the particle. Requires SplineValue
done

2022-05-06 14:33 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +    constexpr int ncomp = ParticleVelocity::extent_1;
done

2022-05-06 14:41 UTC, kwitaechong commented on src/Picasso_APIC.hpp
> +p2g( const ParticleMass& m_p, const ParticleVelocity& c_p, const GridMass& m_i,
Although this `p2g` apply only when momentum update, it still need to to `c_p` since it include particle velocity u_p + affine matrix B_p.

2022-05-06 17:57 UTC, merged