Deprecated cajita
picassodev/picasso pull request #95
Opened 2023-09-20 20:29 UTC by kwitaechong

dependent on #94 .

2023-09-28 21:19 UTC, streeve commented
@kwitaechong can you rebase this?

2023-09-29 13:57 UTC, streeve requested changes

2023-10-02 17:51 UTC, kwitaechong commented on src/Picasso_ParticleList.hpp
> -class ParticleList
handled in #98

2023-10-23 20:17 UTC, streeve commented
retest this please.

2023-10-24 13:18 UTC, streeve approved these changes

2023-10-24 13:20 UTC, merged